; Root directory of BCC QA stuff.

BCCQARootDir	= '/home/ricker/Projects/surveys/des/bcc/qa/source/tests/'

; Locations of files to be read by all BCC QA scripts.

BCCQAinput      = '/home/ricker/Projects/surveys/des/bcc/qa/data/'
mockfolder	= BCCQAinput + 'DES_catalog/'
halofile	= BCCQAinput + 'DR8_Mock_halos.fit'
galfile		= BCCQAinput + 'DR8_Mock_galaxies.fit'
altamagfile	= BCCQAinput + 'DR8_Mock_sdss25.fit'
jmagfile	= BCCQAinput + 'DR8_Mock_johnson.fit'

; Locations in which to place output files/plots. Current directory is
; preferred for use with FlashTest.

outputbase	= './'
plotbase	= './'
plotfolder	= './'
mockbase	= './'

; We want to create PNG files from the plots.

makepng		= 1

; Make sure we pick up all of the BCC QA functions.

pathsep		= path_sep(/search_path) 
!PATH		= expand_path('+'+BCCQARootDir+'bccqa/functions/') + $
		  pathsep + !PATH
