subclass_name: AGN_NumberDensities.AGN_NumberDensity
band: g
rest_frame_band: i
Mag_lim: -22.5
z_lim: [0.3, 2.2]
observation: 'SDSS'
validation_range: [15.5, 19.]
agn_flux_fraction: 0.5
no_agn_extinction: true
duty_cycle_on: false
included_by_default: false
description: 'Plot N and N(<mag) distributions for selected magnitude bound and redshift range in specified band and compare with SDSS data from Richards 2006'
