subclass_name: apparent_mag_func_test.ApparentMagFuncTest
band: r
band_lim: [24, 27.5]
observation: 'HSC'
included_by_default: true
description: 'Plot N(<mag) distributions for selected magnitude bounds in specified band and compare with extrpolated fits to HSC deep fields data.'
