subclass_name: BiasVersusRedshift.BiasValidation

requested_columns:
  ra:
    - ra
  dec:
    - dec
  redshift:
    - redshift
  halo_id:
    - halo_id
test_samples:
  z_02_04:
    redshift: {min: 0.2, max: 0.4}
    halo_id: {min: 0, max: 999999999999999999}
  z_04_06:
    redshift: {min: 0.4, max: 0.6}
    halo_id: {min: 0, max: 999999999999999999}
  z_06_08:
    redshift: {min: 0.6, max: 0.8}
    halo_id: {min: 0, max: 999999999999999999}
  z_08_10:
    redshift: {min: 0.8, max: 1.0}
    halo_id: {min: 0, max: 999999999999999999}

test_sample_labels:
  z_02_04: '$0.2 < z < 0.4$'
  z_04_06: '$0.4 < z < 0.6$'
  z_06_08: '$0.6 < z < 0.8$'
  z_08_10: '$0.8 < r < 1.0$'

test_data:
  z_02_04: {data_col: 3, data_err_col: 4}
  z_04_06: {data_col: 5, data_err_col: 6}
  z_06_08: {data_col: 7, data_err_col: 8}
  z_08_10: {data_col: 9, data_err_col: 10}

output_filename_template: 'w_theta_{}.dat'
label_template: '${} < z < {}$'

data_filename: 'tpcf/Wang_2013_MNRAS_stt450_Table2.txt'
data_label: 'Best fit bias'
fit_range:
  z_02_04: {min_theta: 0.05, max_theta: 0.7}
  z_04_06: {min_theta: 0.05, max_theta: 0.6}
  z_06_08: {min_theta: 0.05, max_theta: 0.5}
  z_08_10: {min_theta: 0.01, max_theta: 0.3}

need_distance: false
fig_xlabel: '$\theta\quad[{\rm deg}]}$'
fig_ylabel: '$w(\theta)$'
fig_ylim: [0.0001, 5.0]

#Treecorr parameters
min_sep: 0.001
max_sep: 10
bin_size: 0.05

description: |
  Compare predicted and computed correlation function
