subclass_name: BiasVersusRedshift.BiasValidation

possible_mag_fields:
  - mag_r_sdss
  - mag_r_des
  - mag_r_lsst
  - mag_true_r_sdss
  - mag_true_r_des
  - mag_true_r_lsst

output_filename_template: 'w_theta_r_{}_{}.dat'
label_template: '${} < z < {}$'

data_filename: 'tpcf/Wang_2013_MNRAS_stt450_Table2.txt'
data_label: 'Y.Wang+2013'
z_bins:
  - {z_min: 0.0, z_max: 0.2, data_col: 3, data_err_col: 4, min_theta: 0.1, max_theta: 1.}
  - {z_min: 0.2, z_max: 0.4, data_col: 5, data_err_col: 6, min_theta: 0.05, max_theta: 0.7}
  - {z_min: 0.4, z_max: 0.6, data_col: 7, data_err_col: 8, min_theta: 0.05, max_theta: 0.6}
  - {z_min: 0.6, z_max: 0.8, data_col: 9, data_err_col: 10, min_theta: 0.05, max_theta: 0.5}
  - {z_min: 0.8, z_max: 1.0, data_col: 1, data_err_col: 2, min_theta: 0.01, max_theta: 0.3}

need_distance: false
fig_xlabel: '$\theta\quad[{\rm deg}]}$'
fig_ylabel: '$w(\theta)$'
fig_ylim: [0.0001, 5.0]

#Treecorr parameters
min_sep: 0.01
max_sep: 15
bin_size: 0.1

description: |
  Compare predicted and computed correlation function
