subclass_name: readiness_test.CheckQuantities
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'

quantities_to_check:
  ellipticity*:
    min: [0, 0.5]
    max: [0.5, 1]
    mean: [0, 1]
    median: [0, 1]
    std: [0, 1]
    finite_frac: 1
    outlier_frac: [0, 0.4]

  mag*:
    min: [0, 20]
    max: [20, 40]
    mean: [20, 30]
    median: [20, 30]
    std: [0, 20]
    finite_frac: 1
    outlier_frac: [0, 0.2]

  size*:
    min: [0, 1]
    max: [1, 10]