subclass_name: CheckQuantities.CheckQuantities
quantities: ['ellipticity{}',['mag_u_lsst', 'mag_r_lsst']]
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'
