subclass_name: ColorDistribution.ColorDistribution
obs_r_mag_limit: 24
zlo: 1.0
zhi: 2.0
plot_pdf_q: true
plot_cdf_q: false
color_transformation_q: false
description: Inspect the mock-galaxy observer-frame color distributions
