subclass_name: ColorDistribution.ColorDistribution
Mag_r_limit: -19.0
rest_frame: true
lightcone: false
plot_pdf_q: true
plot_cdf_q: false
color_transformation_q: false
description: Inspect the mock-galaxy snapshot rest-frame color distributions
