subclass_name: ColorDistribution.ColorDistribution
obs_r_mag_limit: 17.7
zlo: 0.05
zhi: 0.1
validation_catalog: SDSS
use_lsst: true
plot_pdf_q: true
plot_cdf_q: false
color_transformation_q: true
truncate_cat_name: true
replace_cat_name: {'dc2':'DC2'}
legend_size: 12
font_size: 18
plot_shift: false
description: Compare the mock galaxy color distribution with SDSS