subclass_name: EllipticityDistribution.EllipticityDistribution
zlo: 0.
zhi: 2.
N_ebins: 40
observation: 'COSMOS_2013'
normed: True
validation_percentile_points:
  - 10
  - 50
  - 90
validation_percentile_ranges:
  - [0, 0.4]
  - [0.3, 0.7]
  - [0.6, 1]
truncate_cat_name: true
title_in_legend: true
yfont_size: 14
xfont_size: 12
legend_size: 10
legend_title_size: 10

description: 'Plot ellipticity distributions and compare with distributions from Joachimi et al 2013 COSMOS data'
