subclass_name: NumberDensityVersusRedshift.NumberDensityVersusRedshift
band: r
zlo: 0.
zhi: 1.0
N_zbins: 10
observation: 'Coil2004_maglim'
description: 'Plot N(z) distributions for selected magnitude cuts in specified band and compare with fits to DEEP2 data from Coil et. al. (2004).'
