subclass_name: readiness_test_parallel.CheckQuantities
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'
included_by_default: true

quantities_to_check:
  - quantities: ['ra', 'dec']
    label: 'deg'
    min: [-2.51, -2.49]
    max: [2.49, 2.51]
    f_inf: 0


  - quantities: ['blendedness']
    label: redshift
    min: [-0.05, 0.05]
    max: [0.95, 1.05]
    f_inf: 0

  - quantities: 'cModelFlux_i'
    label: 'Ellipticity'
    min: [-0.2, 0]
    max: [0, 0.2]
    f_inf: 0


  - quantities: 'psFlux_g'
    label: 'position angle'
    min: [0, 0.001]
    max: [179.99, 180]
    f_inf: 0

  - quantities: 'mag_g'
    label: mag
    min: [null, 15]
    max: [25, null]
    f_inf: 0

  - quantities: 'mag_r'
    label: mag
    min: [null, 15]
    max: [25, null]
    f_inf: 0

  - quantities: 'mag_u'
    label: mag
    min: [null, 15]
    max: [25, null]
    f_inf: 0

  - quantities: 'mag_z'
    label: mag
    min: [null, 15]
    max: [25, null]
    f_inf: 0

