subclass_name: readiness_test.CheckQuantities
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'

quantities_to_check:
  - quantities: ['ra_true', 'ra', 'dec_true', 'dec']
    label: 'deg'
    min: [-2.51, -2.49]
    max: [2.49, 2.51]
    median: [-0.1, 0.1]
    mean: [-0.05, 0.05]
    std: [1, 2]
    f_nan: 0
    f_inf: 0
    f_outlier: 0

  - quantities: ['redshift_true', 'redshift']
    label: redshift
    min: [-0.05, 0.05]
    max: [0.95, 1.05]
    median: [0.6, 0.8]
    mean: [0.6, 0.8]
    std: [0.1, 0.3]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.001]

  - quantities: 'ellipticity_[12]*'
    label: ellipticity
    min: [-1, -0.8]
    max: [0.8, 1]
    median: [-0.05, 0.05]
    mean: [-0.05, 0.05]
    std: [0.1, 0.4]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.03]

  - quantities: ['ellipticity', 'ellipticity_[!12]*']
    label: ellipticity_total
    min: [0, 0.01]
    max: [0.8, 1]
    median: [0, 1]
    mean: [0, 1]
    std: [0.1, 0.4]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.02]

  - quantities: 'size*'
    label: size
    log: true
    min: [-6, -4]
    max: [1, 3]
    median: [-2, 0]
    mean: [-2, 0]
    std: [0.1, 0.5]
    f_nan: 0
    f_zero: 0
    f_inf: [0, 0.3]
    f_outlier: [0, 0.01]

  - quantities: size*_bulge*
    f_nan: 0
    f_inf: 0
    min: [0, null]

  - quantities: 'shear_*'
    min: [-0.1, 0]
    max: [0, 0.1]
    median: [-0.01, 0.01]
    mean: [-0.01, 0.01]
    std: [0, 0.01]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.03]

  - quantities: 'position_angle*'
    min: [0, 0.001]
    max: [179.99, 180]
    median: [89.9, 90.1]
    mean: [89.9, 90.1]
    std: [0, 90.0]
    f_nan: 0
    f_inf: 0
    f_outlier: 0

  - quantities: 'convergence'
    min: [-0.3, 0]
    max: [0, 0.3]
    median: [-0.01, 0.01]
    mean: [-0.01, 0.01]
    std: [0, 0.02]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.03]

  - quantities: 'magnification'
    min: [0.5, 1]
    max: [1, 2]
    median: [0.5, 1.5]
    mean: [0.5, 1.5]
    std: [0, 0.1]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.03]

  - quantities: 'sersic_disk'
    min: 1
    max: 1
    median: 1
    mean: 1
    std: 0
    f_nan: 0
    f_inf: 0
    f_zero: 0
    f_outlier: 0

  - quantities: 'sersic_bulge'
    min: 4
    max: 4
    median: 4
    mean: 4
    std: 0
    f_nan: 0
    f_inf: 0
    f_zero: 0
    f_outlier: 0

  - quantities: 'mag_*'
    label: mag
    min: [null, 15]
    max: [25, null]
    mean: [20, 30]
    median: [20, 30]
    std: [0, 5]
    f_nan: 0
    f_inf: 0
    f_zero: 0
    f_outlier: [0, 0.05]

  - quantities: 'stellar_mass*'
    log: true
    min: [null, 10]
    max: [10, 13]
    median: [7.5, 9]
    mean: [7.5, 9]
    std: [0.5, 1.5]
    f_nan: 0
    f_outlier: [0, 0.02]

  - quantities: 'sed_*_*[0123456789]'
    label: SED
    log: true
    min: [2, 7]
    max: [9, 11]
    mean: [5, 8]
    median: [5, 8]
    std: [0.5, 1.3]
    f_nan: 0
    f_inf: 0
    f_zero: 0
    f_outlier: [0, 0.03]

  - quantities: 'sed_*_*_disk'
    label: Disk SED
    log: true
    min: [-23.0, -20.0]
    max: [9, 10]
    median: [5, 7]
    mean: [5, 7]
    std: [1, 2]
    f_nan: 0
    f_zero: 0
    f_outlier: [0, 0.1]

  - quantities: 'sed_*_*_bulge'
    label: Bulge SED
    log: true
    min: [-12.0, -7.0]
    max: [9, 11]
    median: [3, 7]
    mean: [3, 7]
    std: [0.5, 1.5]
    f_nan: 0
    f_zero: 0
    f_outlier: [0, 0.03]

  - quantities: A_v
    min: [0.001, 3.1]
    max: [0.001, 3.1]
    median: [0.001, 3.1]
    mean: [0.001, 3.1]
    f_nan: 0
    f_inf: 0

  - quantities: R_v
    min: [1, 5]
    max: [1, 5]
    median: [1, 5]
    mean: [1, 5]
    f_nan: 0
    f_inf: 0

  - quantities: bulge_to_total_ratio*
    min: [0, 1]
    max: [0, 1]
    median: [0, 1]
    mean: [0, 1]
    f_nan: 0
    f_inf: 0

relations_to_check:
  - 'size_minor_bulge_true <= size_bulge_true'
  - 'size_minor_disk_true <= size_disk_true'
  - 'size_minor_true <= size_true'
  - '(size_bulge_true != 0) | (stellar_mass_bulge == 0)'
  - 'stellar_mass_bulge <= stellar_mass'
  - 'stellar_mass_disk <= stellar_mass'
  - '1.0 / magnification ~== (1.0 - convergence)**2.0 - shear_1**2.0 - shear_2**2.0'
  - 'size_minor_true / size_true ~== (1.0 - ellipticity_true) / (1.0 + ellipticity_true)'
  - 'size_minor_disk_true / size_disk_true ~== (1.0 - ellipticity_disk_true) / (1.0 + ellipticity_disk_true)'
  - 'size_minor_bulge_true / size_bulge_true ~== (1.0 - ellipticity_bulge_true) / (1.0 + ellipticity_bulge_true)'
  - 'ellipticity_1_true ** 2.0 + ellipticity_2_true ** 2.0 ~== ellipticity_true ** 2.0'
  - 'ellipticity_1_disk_true ** 2.0 + ellipticity_2_disk_true ** 2.0 ~== ellipticity_disk_true ** 2.0'
  - 'ellipticity_1_bulge_true ** 2.0 + ellipticity_2_bulge_true ** 2.0 ~== ellipticity_bulge_true ** 2.0'
