subclass_name: readiness_test.CheckQuantities
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'

quantities_to_check:
  ellipticity_[12]*:
    min: [-1, -0.8]
    max: [0.8, 1]
    mean: [-0.05, 0.05]
    median: [-0.05, 0.05]
    std: [0.1, 0.4]
    finite_frac: 1
    outlier_frac: [0, 0.05]

  mag_*:
    min: [null, 15]
    max: [25, null]
    mean: [20, 30]
    median: [20, 30]
    std: [0, 5]
    finite_frac: 1
    outlier_frac: [0, 0.05]

  size*:
    log: true
    finite_frac: 1
    outlier_frac: [0, 0.05]

  ra_true:
    std: [1, null]
    finite_frac: 1

  dec_true:
    std: [1, null]
    finite_frac: 1

  redshift_true:
    min: [-0.5, 0.5]
    finite_frac: 1