subclass_name: readiness_test.CheckQuantities
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'
included_by_default: true

catalog_filters:
  - quantity: 'obs_sm'
    label: 'M*'
    min: 1e7

quantities_to_check:
  - quantities: ['dec_true', 'dec']
    label: 'deg'
    min: [-55, -54]
    max: [-20, -19]
    median: [-38, -34]
    mean: [-38, -34]
    std: [5, 10]
    f_nan: 0
    f_inf: 0
    f_outlier: 0

  - quantities: ['ra_true', 'ra']
    label: 'deg'
    min: [39, 40]
    max: [84, 85]
    median: [60, 64]
    mean: [60, 64]
    std: [8, 12]
    f_nan: 0
    f_inf: 0
    f_outlier: 0

  - quantities: ['redshift_true', 'redshift']
    label: redshift
    min: [-0.05, 0.05]
    max: [2.95, 3.05]
    median: [1.8, 2.2]
    mean: [1.8, 2.2]
    std: [0.6, 0.7]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.001]

  - quantities: 'velocity_*'
    label: velocity
    min: [-10500., -9500.]
    max: [9500., 10500.]
    median: [-100., 100.]
    mean: [-100., 100.]
    std: [200., 600.]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.1]

  - quantities: 'shear_*'
    min: [-0.25, 0]
    max: [0, 0.25]
    median: [-0.01, 0.01]
    mean: [-0.01, 0.01]
    std: [0, 0.02]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.04]

  - quantities: 'position_angle*'
    min: [0, 0.001]
    max: [179.99, 180]
    median: [89.9, 90.1]
    mean: [89.9, 90.1]
    std: [0, 90.0]
    f_nan: 0
    f_inf: 0
    f_outlier: 0

  - quantities: 'convergence'
    min: [-0.4, 0]
    max: [0, 0.8]
    median: [-0.01, 0.01]
    mean: [-0.01, 0.01]
    std: [0, 0.03]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.05]

  - quantities: 'magnification'
    min: [0.5, 1]
    max: [1, 20]
    median: [0.5, 1.5]
    mean: [0.5, 1.5]
    std: [0, 0.1]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.05]

  - quantities: 'Mag_*lsst*'
    label: Mag
    min: [null, -23]
    max: [-12, null]
    mean: [-17, -8]
    median: [-17, -8]
    std: [0, 5]
    f_nan: 0
    f_inf: 0
    f_zero: 0
    f_outlier: [0, 0.05]

  - quantities: 'stellar_mass*'
    log: true
    min: [null, 10]
    max: [10, 13]
    median: [5.5, 7]
    mean: [5.5, 7]
    std: [0.5, 1.5]
    f_nan: 0
    f_outlier: [0, 0.025]

relations_to_check:
  - 'galaxy_id < 1e11'
  - '1.0 / magnification ~== (1.0 - convergence)**2.0 - shear_1**2.0 - shear_2**2.0'

uniqueness_to_check:
  - quantity: galaxy_id
  - quantity: halo_id
    mask: is_central
