subclass_name: readiness_test.CheckQuantities
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'

quantities_to_check:
  - quantities: ['ra_true', 'ra', 'dec_true', 'dec']
    label: 'deg'
    min: [-2.51, -2.49]
    max: [2.49, 2.51]
    median: [-0.1, 0.1]
    mean: [-0.05, 0.05]
    std: [1, 2]
    f_nan: 0
    f_inf: 0
    f_outlier: 0

  - quantities: ['redshift_true', 'redshift']
    label: redshift
    min: [-0.05, 0.05]
    max: [0.95, 1.05]
    median: [0.6, 0.8]
    mean: [0.6, 0.8]
    std: [0.1, 0.3]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.001]

  - quantities: 'ellipticity_[12]*'
    label: ellipticity
    min: [-1, -0.8]
    max: [0.8, 1]
    median: [-0.05, 0.05]
    mean: [-0.05, 0.05]
    std: [0.1, 0.4]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.03]

  - quantities: ['ellipticity', 'ellipticity_[!12]*']
    label: ellipticity_total
    min: [0, 0.01]
    max: [0.8, 1]
    median: [0, 1]
    mean: [0, 1]
    std: [0.1, 0.4]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.02]

  - quantities: 'size*'
    label: size
    log: true
    f_nan: 0
    f_inf: [0, 0.3]
    f_outlier: [0, 0.3]

  - quantities: size*_bulge*
    f_nan: 0
    f_inf: 0

  - quantities: 'shear_*'
    min: [-0.1, 0]
    max: [0, 0.1]
    median: [-0.01, 0.01]
    mean: [-0.01, 0.01]
    std: [0, 0.01]
    f_nan: 0
    f_inf: 0
    f_outlier: [0, 0.03]

  - quantities: 'position_angle*'
    min: [0, 0.001]
    max: [179.99, 180]
    median: [89.9, 90.1]
    mean: [89.9, 90.1]
    f_nan: 0
    f_inf: 0
    f_outlier: 0

  - quantities: 'convergence'

  - quantities: 'magnification'

  - quantities: 'sersic_disk'
    min: 1
    max: 1
    median: 1
    mean: 1
    std: 0
    f_nan: 0
    f_inf: 0
    f_zero: 0
    f_outlier: 0

  - quantities: 'sersic_bulge'
    min: 4
    max: 4
    median: 4
    mean: 4
    std: 0
    f_nan: 0
    f_inf: 0
    f_zero: 0
    f_outlier: 0

  - quantities: 'mag_*'
    label: mag
    min: [null, 15]
    max: [25, null]
    mean: [20, 30]
    median: [20, 30]
    std: [0, 5]
    f_nan: 0
    f_inf: 0
    f_zero: 0
    f_outlier: [0, 0.05]
