subclass_name: readiness_test_parallel.CheckQuantities
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'
included_by_default: true

quantities_to_check:
  - quantities: ['ra', 'dec']
    label: 'deg'
    min: [-2.51, -2.49]
    max: [2.49, 2.51]
    f_inf: 0

