subclass_name: shear_test.ShearTest
z: 'redshift_true'
ra: 'ra'
dec: 'dec'
e1: 'shear_1'
e2: 'shear_2_phosim'
kappa: 'convergence'
nbins: 6
min_sep: 1.0
max_sep: 150
sep_units: 'arcmin'
bin_slop: 0.07
zlo: 0.5
zhi: 3.0
ntomo: 3
z_range: 0.05
do_jackknife: False
N_clust: 2
mag: 'Mag_true_r_sdss_z0' 
maglim: -19.0
