subclass_name: SizeStellarMassLuminosity.SizeStellarMassLuminosity

observation: onecomp

possible_mag_fields:
  - Mag_true_g_sdss_z0
  - Mag_true_r_sdss_z0
  - Mag_true_g_des_z0
  - Mag_true_r_des_z0
  - Mag_true_g_lsst_z0
  - Mag_true_r_lsst_z0
  - Mag_true_g_sdss_z01
  - Mag_true_r_sdss_z01
  - Mag_true_g_des_z01
  - Mag_true_r_des_z01
  - Mag_true_g_lsst_z01
  - Mag_true_r_lsst_z01

output_filename_template: 'size_lum_z_{}_{}.dat'
label_template: '${} < z < {}$'

data_filename: 'size/van_der_Wel_2014_ApJ_788_28_Table5_VLuminosity.txt'
data_label: 'van der Wel+2014: comparing mean and scatter'

z_bins:
  - {z_min: 0.0, z_max: 0.5}
  - {z_min: 0.5, z_max: 1.0}
  - {z_min: 1.0, z_max: 1.5}
  - {z_min: 1.5, z_max: 2.0}
  - {z_min: 2.0, z_max: 2.5}
  - {z_min: 2.5, z_max: 3.0}

fig_xlabel: '$\log_{10}(L/L_{\odot}) [{\rm V-band}]$'
fig_ylabel: '$\log_{10}(R_e) [{\rm kpc}]$'

chisq_max: 1.2

description: |
  Compare evolution of size as a function of luminosity and redshift and van der Wel et al (2014) HST-3D and CANDELS observations
