subclass_name: StellarMassFunction.StellarMassFunction
log_Mlo: 9.
log_Mhi: 12.
Nbins: 25
observation: 'PRIMUS_2013'
truncate_cat_name: true
fig_ysize: 16
font_size: 22
text_size: 22
legend_size: 14
description: 'Plot Stellar-Mass Function for various redshift bins and compare with PRIMUS data from Moustakas et. al. (2013)'
included_by_default: true