subclass_name: srv_ngals.CheckNgals
description: 'Check flags'
included_by_default: true
ra: 'ra'
dec: 'dec'

flags_to_check:
  - quantities: 'psFlux_flag_u'
    kind: 'bool'
    flag_val: False

  - quantities: 'good'
    kind: 'bool'
    flag_val: False

  - quantities: 'I_flag'
    kind: 'bool'
    flag_val: False

  - quantities: 'cModelFlux_flag_r'
    kind: 'bool'
    flag_val: False

catalog_filters:

  - filters: ['extendedness==1']
