subclass_name: srv_match.MatchTest
description: 'Interactive Plot'
included_by_default: false

ra: 'ra'
dec: 'dec'
bands: ['r','i','g','u','y','z']

catalog_filters:
  - filters: ['mag_i_cModel<26','detect_isPrimary', 'extendedness==1','detect_isIsolated']

    
#[ 'extendedness==1', 'detect_isPrimary','mag_i_cModel<26']


