subclass_name: readiness_test_synchronous.CheckQuantities
description: 'Plot histograms of listed quantities and perform range, finiteness, mean and standard deviation checks.'
included_by_default: true

subset_size: 100000

quantities_to_check:
  - quantities: ['ra', 'dec']
    kind: 'double'
    label: 'deg'
    min: [-2.51, -2.49]
    max: [2.49, 2.51]
    f_inf: 0

  - quantities: 'cModelFlux_i'
    kind: 'double'
    label: 'cModelFlux'
    min: [-0.2, 0]
    max: [0, 0.2]
    f_inf: 0


  - quantities: 'psFlux_g'
    kind: 'double'
    label: 'psFlux'
    min: [0, 0.001]
    max: [179.99, 180]
    f_inf: 0

  - quantities: 'mag_g'
    kind: 'double'
    label: 'mag_g'
    min: [null, 15]
    max: [25, null]
    f_inf: 0

  - quantities: 'mag_r'
    kind: 'double'
    label: 'mag_r'
    min: [null, 15]
    max: [25, null]
    f_inf: 0

  - quantities: 'mag_u'
    kind: 'double'
    label: 'mag_u'
    min: [null, 15]
    max: [25, null]
    f_inf: 0

  - quantities: 'mag_z'
    kind: 'double'
    label: 'mag_z'
    min: [null, 15]
    max: [25, null]
    f_inf: 0


