subclass_name: srv_analysistools.TestMetric
description: 'test install of analysis tools'
included_by_default: true

ra: 'ra'
dec: 'dec'
models: ['cModel']

bands: ['r','i']

catalog_filters:

  - filters: ['detect_isIsolated','extendedness==0','detect_isPrimary']

mag_lim: 26
snr_lim: 5.0
compare: True
