subclass_name: StellarMassDistribution.StellarMassTest
description: 'Distribution of steellar mass of DC2 catalogue compared with CMASS where the same color and magnitude cuts as CMASS are applied to DC2 galaxies. Number density of DC2 galaxies is compared with that of CMASS and their distribution is plotted'

catalog_name = 'cosmoDC2_v1.1.4_small'
catSize      = 60
