subclass_name: CorrelationsTwoPoint.CorrelationsProjectedTwoPoint

# Catalog columns to attempt to load. The simplified names (e.g. ra, dec) are
# the names that we be used to cut on in test_samples. Make sure these match.
requested_columns:
  ra:
    - ra
    - ra_true
  dec:
    - dec
    - dec_true
  mag_r:
    - Mag_true_r_sdss_z0
    - Mag_true_r_des_z0
    - Mag_true_r_lsst_z0
    - Mag_true_r_sdss_z01
    - Mag_true_r_des_z01
    - Mag_true_r_lsst_z01
  mag_g:
    - Mag_true_g_sdss_z0
    - Mag_true_g_des_z0
    - Mag_true_g_lsst_z0
    - Mag_true_g_sdss_z01
    - Mag_true_g_des_z01
    - Mag_true_g_lsst_z01
  z:
    - redshift
    - redshift_true

# Definition of samples and cuts to apply.  The names of these columns must
# match the simple column name definitions above.
test_samples:
  Mr_-23_-22_blue:
    mag_r: {min: -23, max: -22}
    z: {min: 0.1031, max: 0.2452}
    color: 'mag_g - mag_r*0.97 < 0.21'
  Mr_-22_-21_blue:
    mag_r: {min: -22, max: -21}
    z: {min: 0.0664, max: 0.1589}
    color: 'mag_g - mag_r*0.97 < 0.21'
  Mr_-21_-20_blue:
    mag_r: {min: -21, max: -20}
    z: {min: 0.0420, max: 0.1064}
    color: 'mag_g - mag_r*0.97 < 0.21'
  Mr_-20_-19_blue:
    mag_r: {min: -20, max: -19}
    z: {min: 0.0269, max: 0.0642}
    color: 'mag_g - mag_r*0.97 < 0.21'
  Mr_-23_-22_red:
    mag_r: {min: -23, max: -22}
    z: {min: 0.1031, max: 0.2452}
    color: 'mag_g - mag_r*0.97 >= 0.21'
  Mr_-22_-21_red:
    mag_r: {min: -22, max: -21}
    z: {min: 0.0664, max: 0.1589}
    color: 'mag_g - mag_r*0.97 >= 0.21'
  Mr_-21_-20_red:
    mag_r: {min: -21, max: -20}
    z: {min: 0.0420, max: 0.1064}
    color: 'mag_g - mag_r*0.97 >= 0.21'
  Mr_-20_-19_red:
    mag_r: {min: -20, max: -19}
    z: {min: 0.0269, max: 0.0642}
    color: 'mag_g - mag_r*0.97 >= 0.21'

# Output file naming format for output of the resultant correlation values.
output_filename_template: 'wp_rp_{}.dat'

# Name of file and columns to load and compare against the test samples.
data_filename: 'tpcf/Zehavi_2011_ApJ_736_59_Tables_9_10.txt'
data_label: 'Zehavi+2011'
# Specify the columns to load from the data for comparison. The names here
# should match the sample names from test_samples.
test_data:
  Mr_-23_-22_blue: {data_col: 1, data_err_col: 2}
  Mr_-22_-21_blue: {data_col: 3, data_err_col: 4}
  Mr_-21_-20_blue: {data_col: 5, data_err_col: 6}
  Mr_-20_-19_blue: {data_col: 7, data_err_col: 8}
  Mr_-23_-22_red:  {data_col: 11, data_err_col: 12}
  Mr_-22_-21_red:  {data_col: 13, data_err_col: 14}
  Mr_-21_-20_red:  {data_col: 15, data_err_col: 16}
  Mr_-20_-19_red:  {data_col: 17, data_err_col: 18}

# Plotting configuration.
fig_xlabel: '$r_p\quad[h^{-1}{\rm Mpc}]$'
fig_ylabel: '$w_p(r_p)\quad[h^{-1}{\rm Mpc}]$'
fig_ylim: [0.1, 5000]
test_sample_labels:
  Mr_-23_-22_red: '$-23 < M_r < -22$ (red)'
  Mr_-22_-21_red: '$-22 < M_r < -21$ (red)'
  Mr_-21_-20_red: '$-21 < M_r < -20$ (red)'
  Mr_-20_-19_red: '$-20 < M_r < -19$ (red)'
  Mr_-23_-22_blue: '$-23 < M_r < -22$ (blue)'
  Mr_-22_-21_blue: '$-22 < M_r < -21$ (blue)'
  Mr_-21_-20_blue: '$-21 < M_r < -20$ (blue)'
  Mr_-20_-19_blue: '$-20 < M_r < -19$ (blue)'

fig_subplots: [2, 2]
fig_subplot_groups:
  - [Mr_-23_-22_red, Mr_-23_-22_blue]
  - [Mr_-22_-21_red, Mr_-22_-21_blue]
  - [Mr_-21_-20_red, Mr_-21_-20_blue]
  - [Mr_-20_-19_red, Mr_-20_-19_blue]

pi_maxes: # Line of sight, wp(rp) binning for each sample.
  Mr_-23_-22_blue: 60.0
  Mr_-22_-21_blue: 60.0
  Mr_-21_-20_blue: 60.0
  Mr_-20_-19_blue: 60.0
  Mr_-23_-22_red:  60.0
  Mr_-22_-21_red:  60.0
  Mr_-21_-20_red:  60.0
  Mr_-20_-19_red:  60.0

#Treecorr parameters
min_sep: 0.15
max_sep: 40
bin_size: 0.45
random_mult: 6

description: |
  Compare projected correlation functions of catalog and Zehavi et al (2011) SDSS r-band observations

included_by_default: true
